language: node_js
node_js: "lts/*"
cache:
  directories:
    - "node_modules"

install:
  - npm install
script:
  - npm run test && npm run build

before_deploy:
  - echo 'ready?'

deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  on:
    branch: master